tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  - name: install backend
    init: |
      cd backend-flask
      pip3 install -r requirements.txt
      cd ..
  - name: install frontend
    init: |
      cd frontend-react-js
      npm install
      cd ..
# All the ports to expose From https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend prort
    description: Backend of The application
    port: 4567
    onOpen: open-browser
  - name: Backend prort
    description: Frontend of The application
    port: 3000
    onOpen: open-browser
vscode:
  extensions:
    - 42Crunch.vscode-openapi
